name = input("Enter student name: ")
usn = input("Enter student USN: ")
course=input("Enter student course: ")
colleage=input("Enter student colleage: ")
print("\nStudent Details:")
print("Name:", name)
print("USN:", usn)
print("Course:", course)
print("Colleage:", colleage)
